In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [9]:
mr_data = pd.read_csv('kaggle_3m/data.csv')
mr_data.T

,0,1,2,3,4,5,6,7,8,9,...,100,101,102,103,104,105,106,107,108,109
Patient,TCGA_CS_4941,TCGA_CS_4942,TCGA_CS_4943,TCGA_CS_4944,TCGA_CS_5393,TCGA_CS_5395,TCGA_CS_5396,TCGA_CS_5397,TCGA_CS_6186,TCGA_CS_6188,...,TCGA_HT_8106,TCGA_HT_8107,TCGA_HT_8111,TCGA_HT_8113,TCGA_HT_8114,TCGA_HT_8563,TCGA_HT_A5RC,TCGA_HT_A616,TCGA_HT_A61A,TCGA_HT_A61B
RNASeqCluster,2,1,1,NaN,4,2,3,NaN,2,2,...,2,4,1,4,1,2,2,NaN,NaN,NaN
MethylationCluster,4,5,5,5,5,4,3,4,4,4,...,5,1,5,3,5,5,4,5,5,5
miRNACluster,2,2,2,2,2,2,2,1,1,3,...,3,1,1,1,2,3,2,2,2,2
CNCluster,2,1,1,1,1,2,3,2,2,2,...,1,1,1,1,1,1,2,1,NaN,1
RPPACluster,NaN,1,2,2,2,NaN,2,3,1,3,...,2,4,1,4,1,NaN,NaN,NaN,NaN,NaN
OncosignCluster,3,2,2,1,3,3,2,3,3,3,...,2,3,2,1,2,2,3,2,NaN,2
COCCluster,2,1,1,1,1,2,3,2,2,2,...,2,1,1,1,1,2,2,1,1,1
histological_type,1,1,1,1,1,3,3,1,2,1,...,1,3,2,3,2,1,1,1,3,NaN
neoplasm_histologic_grade,2,2,2,1,2,1,2,2,2,2,...,2,1,2,1,2,2,2,1,1,NaN
tumor_tissue_site,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,NaN
laterality,3,3,1,3,1,3,3,1,3,3,...,2,1,1,1,1,3,1,1,1,NaN
tumor_location,2,2,2,6,6,5,2,6,2,6,...,2,5,2,2,5,2,2,2,6,NaN
gender,2,1,2,2,2,2,1,1,2,2,...,2,2,2,1,2,1,1,1,1,NaN
age_at_initial_pathologic,67,44,37,50,39,43,53,54,58,48,...,53,62,32,49,36,30,70,36,20,NaN
race,3,2,3,3,3,2,3,3,3,3,...,3,3,3,2,3,3,3,3,3,NaN
ethnicity,2,NaN,NaN,NaN,NaN,NaN,2,2,2,2,...,2,2,2,2,2,2,2,2,2,NaN
death01,1,1,0,0,0,1,0,1,1,0,...,0,0,0,0,0,0,1,0,0,NaN

In [13]:
mr_data.isnull().mean()

Patient                      0.000000
RNASeqCluster                0.163636
MethylationCluster           0.009091
miRNACluster                 0.000000
CNCluster                    0.018182
RPPACluster                  0.109091
OncosignCluster              0.045455
COCCluster                   0.000000
histological_type            0.009091
neoplasm_histologic_grade    0.009091
tumor_tissue_site            0.009091
laterality                   0.009091
tumor_location               0.009091
gender                       0.009091
age_at_initial_pathologic    0.009091
race                         0.018182
ethnicity                    0.072727
death01                      0.009091
dtype: float64

In [11]:
ct_data_hemo = pd.read_csv('computed-tomography-images-for-intracranial-hemorrhage-detection-and-segmentation-1.0.0/hemorrhage_diagnosis.csv')
ct_data_hemo.head()

,PatientNumber,SliceNumber,Intraventricular,Intraparenchymal,Subarachnoid,Epidural,Subdural,No_Hemorrhage,Fracture_Yes_No
0,49,1,0,0,0,0,0,1,0
1,49,2,0,0,0,0,0,1,0
2,49,3,0,0,0,0,0,1,0
3,49,4,0,0,0,0,0,1,0
4,49,5,0,0,0,0,0,1,0

In [14]:
ct_data_hemo.isnull().mean()

PatientNumber       0.0
SliceNumber         0.0
Intraventricular    0.0
Intraparenchymal    0.0
Subarachnoid        0.0
Epidural            0.0
Subdural            0.0
No_Hemorrhage       0.0
Fracture_Yes_No     0.0
dtype: float64

In [15]:
ct_data_pat = pd.read_csv('computed-tomography-images-for-intracranial-hemorrhage-detection-and-segmentation-1.0.0/patient_demographics.csv')
ct_data_pat.head()

,Patient Number,Age (years),Gender,Intraventricular,Intraparenchymal,Subarachnoid,Epidural,Subdural,Fracture (Yes/No),Condition on file,Note
0,49,35.000000,Male,NaN,1.0,NaN,1.0,NaN,1.0,Intracranial HGE+ Extradural HGE,NaN
1,50,0.583333,Female,NaN,1.0,NaN,NaN,NaN,1.0,Subdural HGE,NaN
2,51,5.000000,Male,NaN,1.0,NaN,NaN,1.0,1.0,Extadural HGE,NaN
3,52,8.000000,Male,NaN,NaN,NaN,1.0,NaN,1.0,Extadural HGE,NaN
4,53,44.000000,Male,NaN,1.0,NaN,1.0,NaN,1.0,Intracranial HGE+ Extradural HGE,NaN

In [16]:
ct_data_pat.isnull().mean()

Patient Number       0.000000
Age\n(years)         0.000000
Gender               0.000000
Intraventricular     0.939024
Intraparenchymal     0.804878
Subarachnoid         0.914634
Epidural             0.743902
Subdural             0.951220
Fracture (Yes/No)    0.731707
Condition on file    0.000000
Note                 0.987805
dtype: float64